### ISSUE TITLE
Lab instructions state click cancel, user should instead click next and then select SQL Managed Instance from the dropdown

### ISSUE THREAD

**Issue by blakedeckard** [MicrosoftLearning/mslearn-sql-migration#1]
# Module: [00](https://microsoftlearning.github.io/mslearn-sql-migration/Instructions/Labs/01-identify-compatibility-issues.html)
#### Step: 4. Select Cancel and choose Azure SQL Managed Instance instead as the Azure SQL target platform.

Description of issue
It seems in the current version you do not select a target platform, instead you click next and then select your target platform from a drop down.

After step 4 the lab user is on this page, please never mind the assessment results as I had already dropped the next column:
![image](https://github.com/MicrosoftLearning/mslearn-sql-migration/assets/56769700/37c13415-18e1-4eac-bd59-616f8c0ce17d)

However, the lab user should not click cancel -- instead they should click next and then select SQL MI and save the assessment results:
![image](https://github.com/MicrosoftLearning/mslearn-sql-migration/assets/56769700/4b836a49-cb26-483a-8198-516448d1839d)

Repro steps:
Follow instructions until step 4, validate that user should click next and not cancel.

**Comment by JulianePadrao** [comment]
Thanks for your feedback. This issue has been addressed.
