### ISSUE TITLE
Assess a SQL Server databases for migration

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/mslearn-sql-migration#3]
# Module:  LAB01 & LAB03 
#### Step: 4

Description of issue:

SQL command errors multiple times, with different versions of the .bak files and giving system errors trying to access paths to where the downloaded file is found. 

"Cannot open backup device "Adventure....20XX.bak" file."

Repro steps:

1. Very command works, which .bak file to download and a location .bak file should be stored in.

**Comment by JulianePadrao** [comment]
The script works fine. Make sure to update the file name and the folder path once you download the .bak here: https://learn.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-ver16&tabs=ssms#download-backup-files, as instructed in the **before you start** section.

Thank you.
